/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmgmt;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author kapil
 */
public class AddStudent extends javax.swing.JFrame {

    /**
     * Creates new form AddStudent
     */
    public AddStudent() {
        initComponents();
        initAction();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        schoolNameLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        middleNamejTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        dobTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fatherNameTextField = new javax.swing.JTextField();
        motherNameTextField = new javax.swing.JTextField();
        firstNameTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        maleRadio = new javax.swing.JRadioButton();
        femaleRadio = new javax.swing.JRadioButton();
        localAddTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        stateTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        pincodeTextField = new javax.swing.JTextField();
        distTextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        permAddTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        studentContactTextField = new javax.swing.JTextField();
        fatherContactTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        eadharTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        samagraIdTextField = new javax.swing.JTextField();
        familyIdTextField = new javax.swing.JTextField();
        accountNumberTextField = new javax.swing.JTextField();
        scholarNoTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        generalRadio = new javax.swing.JRadioButton();
        obcRadio = new javax.swing.JRadioButton();
        othercRadio = new javax.swing.JRadioButton();
        stscRadio1 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        ClassComboBox = new javax.swing.JComboBox<>();
        ifscTextField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        ClassCatComboBox = new javax.swing.JComboBox<>();
        addmissionYearTextField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        preSchoolNameTextField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        feesTextField = new javax.swing.JTextField();
        bankNameTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        schoolNameLabel.setBackground(new java.awt.Color(0, 51, 153));
        schoolNameLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        schoolNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        schoolNameLabel.setText("School Name");
        schoolNameLabel.setOpaque(true);
        getContentPane().add(schoolNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 80));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 610, 100, 30));

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancel");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 51)));
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 610, 100, 30));

        jLabel1.setBackground(new java.awt.Color(0, 153, 204));
        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 1370, 45));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel2.setText("Parent Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, -1, 30));

        middleNamejTextField.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        middleNamejTextField.setForeground(new java.awt.Color(153, 153, 153));
        middleNamejTextField.setText("Middle Name");
        middleNamejTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        middleNamejTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                middleNamejTextFieldFocusGained(evt);
            }
        });
        middleNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middleNamejTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(middleNamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 130, 25));

        lastNameTextField.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        lastNameTextField.setForeground(new java.awt.Color(153, 153, 153));
        lastNameTextField.setText("Last Name");
        lastNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        lastNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNameTextFieldFocusGained(evt);
            }
        });
        getContentPane().add(lastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 200, 25));

        dobTextField.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        dobTextField.setForeground(new java.awt.Color(153, 153, 153));
        dobTextField.setText("YYYY-MM-DD");
        dobTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        dobTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dobTextFieldFocusGained(evt);
            }
        });
        getContentPane().add(dobTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 185, 200, 25));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel3.setText("Gender");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 185, -1, 30));

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel4.setText("Student Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 30));

        fatherNameTextField.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        fatherNameTextField.setForeground(new java.awt.Color(153, 153, 153));
        fatherNameTextField.setText("Father Name");
        fatherNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        fatherNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fatherNameTextFieldFocusGained(evt);
            }
        });
        fatherNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatherNameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(fatherNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 150, 220, 25));

        motherNameTextField.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        motherNameTextField.setForeground(new java.awt.Color(153, 153, 153));
        motherNameTextField.setText("Mothre Name");
        motherNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        motherNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                motherNameTextFieldFocusGained(evt);
            }
        });
        getContentPane().add(motherNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 150, 210, 25));

        firstNameTextField.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        firstNameTextField.setForeground(new java.awt.Color(153, 153, 153));
        firstNameTextField.setText("First Name");
        firstNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        firstNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstNameTextFieldFocusGained(evt);
            }
        });
        getContentPane().add(firstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 200, 25));

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel5.setText("Date Of Birth");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 185, -1, 30));

        maleRadio.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        maleRadio.setText("Male");
        getContentPane().add(maleRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 185, -1, -1));

        femaleRadio.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        femaleRadio.setText("Female");
        getContentPane().add(femaleRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 185, -1, -1));

        localAddTextField.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        localAddTextField.setForeground(new java.awt.Color(153, 153, 153));
        localAddTextField.setText("eg. Bhopal");
        localAddTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        localAddTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                localAddTextFieldFocusGained(evt);
            }
        });
        getContentPane().add(localAddTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 255, 550, 25));

        jLabel8.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel8.setText("City or Town");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 30));

        jLabel10.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel10.setText("Local Add");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 255, -1, 30));

        jLabel11.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel11.setText("State ");
        jLabel11.setToolTipText("");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, 30));

        stateTextField.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        stateTextField.setForeground(new java.awt.Color(153, 153, 153));
        stateTextField.setText("Madhya Pradesh");
        stateTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        stateTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stateTextFieldFocusGained(evt);
            }
        });
        getContentPane().add(stateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 270, 25));

        jLabel14.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel14.setText("District");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, -1, 30));

        pincodeTextField.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        pincodeTextField.setForeground(new java.awt.Color(153, 153, 153));
        pincodeTextField.setText("Pincode");
        pincodeTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        pincodeTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pincodeTextFieldFocusGained(evt);
            }
        });
        getContentPane().add(pincodeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 220, 210, 25));

        distTextField.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        distTextField.setForeground(new java.awt.Color(153, 153, 153));
        distTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        distTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                distTextFieldFocusGained(evt);
            }
        });
        getContentPane().add(distTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 220, 220, 25));

        cityTextField.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        cityTextField.setForeground(new java.awt.Color(153, 153, 153));
        cityTextField.setText("eg. Bhopal");
        cityTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        cityTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cityTextFieldFocusGained(evt);
            }
        });
        getContentPane().add(cityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 200, 25));

        permAddTextField.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        permAddTextField.setForeground(new java.awt.Color(153, 153, 153));
        permAddTextField.setText("eg. Bhopal");
        permAddTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        permAddTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                permAddTextFieldFocusGained(evt);
            }
        });
        getContentPane().add(permAddTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 255, 440, 25));

        jLabel17.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel17.setText("Permanent Add");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 255, -1, 30));

        jLabel18.setBackground(new java.awt.Color(0, 153, 204));
        jLabel18.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(" Student Details");
        jLabel18.setOpaque(true);
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1370, 35));

        jLabel12.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel12.setText("Taking addmission");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, 30));

        studentContactTextField.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        studentContactTextField.setForeground(new java.awt.Color(153, 153, 153));
        studentContactTextField.setText("Student Contact");
        studentContactTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        studentContactTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                studentContactTextFieldFocusGained(evt);
            }
        });
        studentContactTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentContactTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(studentContactTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 220, 25));

        fatherContactTextField.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        fatherContactTextField.setForeground(new java.awt.Color(153, 153, 153));
        fatherContactTextField.setText("Father Contact");
        fatherContactTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        fatherContactTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fatherContactTextFieldFocusGained(evt);
            }
        });
        getContentPane().add(fatherContactTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 220, 25));

        emailTextField.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        emailTextField.setForeground(new java.awt.Color(153, 153, 153));
        emailTextField.setText("eg. K123@gmail.com");
        emailTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        emailTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTextFieldFocusGained(evt);
            }
        });
        getContentPane().add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 340, 440, 25));

        jLabel19.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel19.setText("Email Id");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, -1, 30));

        eadharTextField.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        eadharTextField.setForeground(new java.awt.Color(153, 153, 153));
        eadharTextField.setText("400020201020");
        eadharTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        eadharTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                eadharTextFieldFocusGained(evt);
            }
        });
        getContentPane().add(eadharTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 220, 25));

        jLabel9.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel9.setText("Eadhar No.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 30));

        jLabel13.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel13.setText("Scholar No.");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, -1, 30));
        jLabel13.getAccessibleContext().setAccessibleName("Samagra Id");

        samagraIdTextField.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        samagraIdTextField.setForeground(new java.awt.Color(153, 153, 153));
        samagraIdTextField.setText("Student Id");
        samagraIdTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        samagraIdTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                samagraIdTextFieldFocusGained(evt);
            }
        });
        samagraIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samagraIdTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(samagraIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 370, 220, 25));

        familyIdTextField.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        familyIdTextField.setForeground(new java.awt.Color(153, 153, 153));
        familyIdTextField.setText("Family ID");
        familyIdTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        familyIdTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                familyIdTextFieldFocusGained(evt);
            }
        });
        getContentPane().add(familyIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 370, 210, 25));

        accountNumberTextField.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        accountNumberTextField.setForeground(new java.awt.Color(153, 153, 153));
        accountNumberTextField.setText("Account number");
        accountNumberTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        accountNumberTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                accountNumberTextFieldFocusGained(evt);
            }
        });
        accountNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountNumberTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(accountNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 220, 25));

        scholarNoTextField.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        scholarNoTextField.setForeground(new java.awt.Color(153, 153, 153));
        scholarNoTextField.setText("Scholar no.");
        scholarNoTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        scholarNoTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                scholarNoTextFieldFocusGained(evt);
            }
        });
        getContentPane().add(scholarNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 480, 140, 25));

        jLabel20.setBackground(new java.awt.Color(0, 153, 204));
        jLabel20.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText(" Contact Details");
        jLabel20.setOpaque(true);
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 1370, 35));

        jLabel21.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel21.setText("Category");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, -1, 30));

        generalRadio.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        generalRadio.setText("General");
        getContentPane().add(generalRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 180, -1, -1));

        obcRadio.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        obcRadio.setText("OBC");
        getContentPane().add(obcRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 180, -1, -1));

        othercRadio.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        othercRadio.setText("Other");
        getContentPane().add(othercRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 180, -1, -1));

        stscRadio1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        stscRadio1.setText("St/sc");
        getContentPane().add(stscRadio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 180, -1, -1));

        jLabel16.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel16.setText("Mobile No.");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 30));

        ClassComboBox.setBackground(new java.awt.Color(0, 0, 0));
        ClassComboBox.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        ClassComboBox.setForeground(new java.awt.Color(255, 255, 255));
        ClassComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(ClassComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 90, 25));

        ifscTextField.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        ifscTextField.setForeground(new java.awt.Color(153, 153, 153));
        ifscTextField.setText("IFSC");
        ifscTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        ifscTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ifscTextFieldFocusGained(evt);
            }
        });
        getContentPane().add(ifscTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 220, 25));

        jLabel22.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel22.setText("Account No.");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 30));

        jLabel23.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel23.setText("Samagra ID");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 370, -1, 30));

        ClassCatComboBox.setBackground(new java.awt.Color(0, 0, 0));
        ClassCatComboBox.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        ClassCatComboBox.setForeground(new java.awt.Color(255, 255, 255));
        ClassCatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(ClassCatComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 90, 25));

        addmissionYearTextField.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        addmissionYearTextField.setForeground(new java.awt.Color(153, 153, 153));
        addmissionYearTextField.setText("YYYY");
        addmissionYearTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        addmissionYearTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addmissionYearTextFieldFocusGained(evt);
            }
        });
        getContentPane().add(addmissionYearTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 480, 140, 25));

        jLabel24.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel24.setText("Addmission year");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 480, -1, 30));

        jLabel6.setBackground(new java.awt.Color(0, 153, 204));
        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Academic Details");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 1370, 35));

        preSchoolNameTextField.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        preSchoolNameTextField.setForeground(new java.awt.Color(153, 153, 153));
        preSchoolNameTextField.setText("School Name");
        preSchoolNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        preSchoolNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                preSchoolNameTextFieldFocusGained(evt);
            }
        });
        getContentPane().add(preSchoolNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 410, 25));

        jLabel25.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel25.setText("Previous School");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, 30));

        jLabel26.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel26.setText("Due Fees");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 520, -1, 30));

        feesTextField.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        feesTextField.setForeground(new java.awt.Color(153, 153, 153));
        feesTextField.setText("fees");
        feesTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        feesTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                feesTextFieldFocusGained(evt);
            }
        });
        getContentPane().add(feesTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 520, 140, 25));

        bankNameTextField.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        bankNameTextField.setForeground(new java.awt.Color(153, 153, 153));
        bankNameTextField.setText("Bank Name");
        bankNameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        bankNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bankNameTextFieldFocusGained(evt);
            }
        });
        getContentPane().add(bankNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 220, 25));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void middleNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middleNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middleNamejTextFieldActionPerformed

    private void fatherNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatherNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherNameTextFieldActionPerformed

    private void studentContactTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentContactTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentContactTextFieldActionPerformed

    private void samagraIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samagraIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_samagraIdTextFieldActionPerformed

    private void accountNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountNumberTextFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void firstNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameTextFieldFocusGained
            firstNameTextField.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldFocusGained

    private void middleNamejTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_middleNamejTextFieldFocusGained
        middleNamejTextField.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_middleNamejTextFieldFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      Sql sql = new Sql(this);
      Student st =new Student();
      int cl=0;
      String classcat="";
      int ci = ClassComboBox.getSelectedIndex();
      if(ci == 1){
         classcat = "N";
      }else if(ci == 2){
         classcat = "K1";
      }else if(ci == 3){
         classcat = "K2";
      }else{
          cl = ci-3;
          switch(ClassCatComboBox.getSelectedIndex()){
              case 0:
                  classcat="M";
                  break;
              case 1:
                  classcat="B";
                  break;
              case 2:
                  classcat="C";
                  break;
              case 3:
                  classcat="Ar";
                  break;
              case 4:
                  classcat="Ag";
                  break;
          }
          if(cl>=1 && cl<=10){
              classcat = "k";
          }
      }
      String gender = "";
      String category = "";
      //gender button 
      if(maleRadio.isSelected()){
      gender = "M";
      }
      else{
      gender = "F";
      }
      if(generalRadio.isSelected()){
      category = "General";
      }
      else if(obcRadio.isSelected()){
      category = "OBC";
      }
      else if(stscRadio1.isSelected()){
      category = "SC/ST";
      }
      else{
      category = "Other";
      }
      
      try{
      st.setFname(firstNameTextField.getText());
      st.setlName(lastNameTextField.getText());
      st.setmName(middleNamejTextField.getText());
      st.setCity(cityTextField.getText());
      st.setClass(cl);
      st.setRollNo(0);
      st.setClassCat(classcat);
      st.setDOB(dobTextField.getText());
      st.setGender(gender);
      st.setCategory(category);
      st.setCity(cityTextField.getText());
      st.setEadharNo(eadharTextField.getText());
      st.setLocalAddress(localAddTextField.getText());
      st.setPermanentAddress(permAddTextField.getText());
      st.setFatherName(fatherNameTextField.getText());
      st.setMotherName(motherNameTextField.getText());
      st.setStudentContact(studentContactTextField.getText());
      st.setFatherContact(fatherContactTextField.getText());
      st.setEmail(emailTextField.getText());
      st.setPinCode(pincodeTextField.getText());
      st.setSamagraId(samagraIdTextField.getText());
      st.setFamilyId(familyIdTextField.getText());
      st.setDist(distTextField.getText());
      st.setState(stateTextField.getText());
      st.setAddmissionYear(addmissionYearTextField.getText());
      st.setScholarNumber(Integer.valueOf(scholarNoTextField.getText()));
      st.setPreviousSchool(preSchoolNameTextField.getText());
      st.setBankName(ifscTextField.getText());
      st.setIFSC(ifscTextField.getText());
      st.setFees(Double.valueOf(feesTextField.getText()));
      st.setAccountNumber(accountNumberTextField.getText());
          if(validation())
          {
              if(sql.addStudent(st)){
              JOptionPane.showMessageDialog(this, "Student Added Successfully");
             }
              else{
              JOptionPane.showMessageDialog(this, "Student not added. ");
              }
          }     
          else
          {
              JOptionPane.showMessageDialog(this, "Fill Form Completly.");
              return;
          }
      }catch(Exception e){ 
          JOptionPane.showMessageDialog(this, "Cannot Add Student");
          e.printStackTrace();
      }
      // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ifscTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ifscTextFieldFocusGained
         ifscTextField.setText("");
    }//GEN-LAST:event_ifscTextFieldFocusGained

    private void lastNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameTextFieldFocusGained
        lastNameTextField.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldFocusGained

    private void dobTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dobTextFieldFocusGained
        dobTextField.setText("1990-12-31");
        // TODO add your handling code here:
    }//GEN-LAST:event_dobTextFieldFocusGained

    private void cityTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityTextFieldFocusGained
        cityTextField.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTextFieldFocusGained

    private void stateTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stateTextFieldFocusGained
        stateTextField.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_stateTextFieldFocusGained

    private void localAddTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_localAddTextFieldFocusGained
        localAddTextField.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_localAddTextFieldFocusGained

    private void permAddTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_permAddTextFieldFocusGained
        permAddTextField.setText("");
            // TODO add your handling code here:
    }//GEN-LAST:event_permAddTextFieldFocusGained

    private void fatherNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fatherNameTextFieldFocusGained
        fatherNameTextField.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherNameTextFieldFocusGained

    private void motherNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_motherNameTextFieldFocusGained
        motherNameTextField.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_motherNameTextFieldFocusGained

    private void distTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_distTextFieldFocusGained
        distTextField.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_distTextFieldFocusGained

    private void pincodeTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pincodeTextFieldFocusGained
        pincodeTextField.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_pincodeTextFieldFocusGained

    private void studentContactTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentContactTextFieldFocusGained
        studentContactTextField.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_studentContactTextFieldFocusGained

    private void eadharTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_eadharTextFieldFocusGained
            eadharTextField.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_eadharTextFieldFocusGained

    private void accountNumberTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_accountNumberTextFieldFocusGained
        accountNumberTextField.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_accountNumberTextFieldFocusGained

    private void fatherContactTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fatherContactTextFieldFocusGained
        fatherContactTextField.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_fatherContactTextFieldFocusGained

    private void bankNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bankNameTextFieldFocusGained
        bankNameTextField.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_bankNameTextFieldFocusGained

    private void samagraIdTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_samagraIdTextFieldFocusGained
        samagraIdTextField.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_samagraIdTextFieldFocusGained

    private void familyIdTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_familyIdTextFieldFocusGained
        familyIdTextField.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_familyIdTextFieldFocusGained

    private void emailTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFieldFocusGained
        emailTextField.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldFocusGained

    private void preSchoolNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_preSchoolNameTextFieldFocusGained
        preSchoolNameTextField.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_preSchoolNameTextFieldFocusGained

    private void scholarNoTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_scholarNoTextFieldFocusGained
        scholarNoTextField.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_scholarNoTextFieldFocusGained

    private void addmissionYearTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addmissionYearTextFieldFocusGained
        addmissionYearTextField.setText("20");
        // TODO add your handling code here:
    }//GEN-LAST:event_addmissionYearTextFieldFocusGained

    private void feesTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_feesTextFieldFocusGained
        int cl = ClassComboBox.getSelectedIndex();
        String classcat = "0";
        switch(cl){
            case 1:
                cl=0;
                classcat = "N";
                break;
            case 2:
                cl=0;
                classcat = "K1";
                break;
            case 3:
                cl=0;
                classcat = "K2";
                break;
            default :
                cl -= 3;
        }
        double fees = new Sql().getFess(cl, classcat);
        feesTextField.setText(String.valueOf(fees));
    }//GEN-LAST:event_feesTextFieldFocusGained
public void initAction(){
    setExtendedState(MAXIMIZED_BOTH);
    setVisible(true);
    setBackground(Color.white);
    schoolNameLabel.setText(SchoolMgmt.schoolName);
    setTitle("Add Student");
    genderRadio();   
}


public void genderRadio(){
cat = new ButtonGroup();
gen = new ButtonGroup();
gen.add(maleRadio);
gen.add(femaleRadio);
maleRadio.setSelected(true);
cat = new ButtonGroup();
cat.add(generalRadio);
cat.add(obcRadio);
cat.add(stscRadio1);
cat.add(othercRadio);
generalRadio.setSelected(true);
ClassComboBox.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        if(ClassComboBox.getSelectedIndex() >= 14)
            ClassCatComboBox.setEnabled(true);
    }
});

ClassComboBox.removeAllItems();
ClassCatComboBox.removeAllItems();
ClassCatComboBox.setEnabled(false);
ClassComboBox.addItem("Select Class");
ClassComboBox.addItem("N");
ClassComboBox.addItem("Kg-1");
ClassComboBox.addItem("Kg-2");
for(int i=1;i<=12;i++)
ClassComboBox.addItem("Class "+i);
ClassCatComboBox.addItem("PCM");
ClassCatComboBox.addItem("PCB");
ClassCatComboBox.addItem("Commerce");
ClassCatComboBox.addItem("Arts");
ClassCatComboBox.addItem("Agriculture");
ClassCatComboBox.setEditable(true);
ClassCatComboBox.setSelectedItem("Commerce");
}

public boolean validation(){
    if(firstNameTextField.equals("")
            || lastNameTextField.equals("")
            || fatherNameTextField.equals("")
            || motherNameTextField.equals("")
            || dobTextField.equals("")
            || dobTextField.equals("YYYY-MM-DD")
            || distTextField.equals("")
            || pincodeTextField.equals("")
            ||localAddTextField.equals("")
            ||permAddTextField.equals("")
            ||studentContactTextField.equals("")
            ||fatherContactTextField.equals("")
            ||emailTextField.equals("")
            ||eadharTextField.equals("")
            ||samagraIdTextField.equals("")
            ||familyIdTextField.equals("")
            ||preSchoolNameTextField.equals("")
            ||scholarNoTextField.equals("")
            ||addmissionYearTextField.equals("")
            ||feesTextField.equals("")
            ){
     return false;
    }
    if(true){
    return true;
    }
return true;
}


  private  ButtonGroup gen;
  private  ButtonGroup cat;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ClassCatComboBox;
    private javax.swing.JComboBox<String> ClassComboBox;
    private javax.swing.JTextField accountNumberTextField;
    private javax.swing.JTextField addmissionYearTextField;
    private javax.swing.JTextField bankNameTextField;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JTextField distTextField;
    private javax.swing.JTextField dobTextField;
    private javax.swing.JTextField eadharTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField familyIdTextField;
    private javax.swing.JTextField fatherContactTextField;
    private javax.swing.JTextField fatherNameTextField;
    private javax.swing.JTextField feesTextField;
    private javax.swing.JRadioButton femaleRadio;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JRadioButton generalRadio;
    private javax.swing.JTextField ifscTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JTextField localAddTextField;
    private javax.swing.JRadioButton maleRadio;
    private javax.swing.JTextField middleNamejTextField;
    private javax.swing.JTextField motherNameTextField;
    private javax.swing.JRadioButton obcRadio;
    private javax.swing.JRadioButton othercRadio;
    private javax.swing.JTextField permAddTextField;
    private javax.swing.JTextField pincodeTextField;
    private javax.swing.JTextField preSchoolNameTextField;
    private javax.swing.JTextField samagraIdTextField;
    private javax.swing.JTextField scholarNoTextField;
    private javax.swing.JLabel schoolNameLabel;
    private javax.swing.JTextField stateTextField;
    private javax.swing.JRadioButton stscRadio1;
    private javax.swing.JTextField studentContactTextField;
    // End of variables declaration//GEN-END:variables
}
