/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmgmt;

import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author kapil
 */
public class FeesPay extends javax.swing.JFrame {

    /**
     * Creates new form FeesPay
     */
    public FeesPay() {
            
        initComponents();
        initData();
        requestFocus();
        this.setResizable(false);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelPhoto = new javax.swing.JLabel();
        jTextFieldComment = new javax.swing.JTextField();
        jTextFieldRollNo = new javax.swing.JTextField();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldFather = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldCity = new javax.swing.JTextField();
        jLabelTitle = new javax.swing.JLabel();
        jTextFieldAmount = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        jLabelTitle1 = new javax.swing.JLabel();
        payButton = new javax.swing.JButton();
        purposeComboBox = new javax.swing.JComboBox<>();
        jTextFieldcontact = new javax.swing.JTextField();
        jComboBoxThrough = new javax.swing.JComboBox<>();
        jLabelTitle2 = new javax.swing.JLabel();
        jLabelTitle3 = new javax.swing.JLabel();
        jLabelTitle4 = new javax.swing.JLabel();
        updateFees = new javax.swing.JPanel();
        jComboBoxClass2 = new javax.swing.JComboBox<>();
        jTextFieldAmount2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        schoolNameLabel = new javax.swing.JLabel();
        studentFees = new javax.swing.JPanel();
        jTextFieldAmount3 = new javax.swing.JTextField();
        jTextFieldId3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        schoolNameLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(700, 430));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(486, 300));
        jPanel1.setMinimumSize(new java.awt.Dimension(486, 300));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPhoto.setBackground(new java.awt.Color(102, 255, 102));
        jLabelPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/warning_icon.gif"))); // NOI18N
        jPanel1.add(jLabelPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 130, 150));

        jTextFieldComment.setColumns(2);
        jTextFieldComment.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        jTextFieldComment.setText("Comment..");
        jTextFieldComment.setOpaque(false);
        jPanel1.add(jTextFieldComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 213, 25));

        jTextFieldRollNo.setColumns(2);
        jTextFieldRollNo.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        jTextFieldRollNo.setText("Roll Number");
        jTextFieldRollNo.setOpaque(false);
        jTextFieldRollNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldRollNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldRollNoFocusLost(evt);
            }
        });
        jTextFieldRollNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldRollNoMouseClicked(evt);
            }
        });
        jTextFieldRollNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRollNoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldRollNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 110, 20));

        jTextFieldID.setColumns(2);
        jTextFieldID.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        jTextFieldID.setText("Student ID Number");
        jTextFieldID.setOpaque(false);
        jTextFieldID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldIDFocusLost(evt);
            }
        });
        jTextFieldID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldIDMouseClicked(evt);
            }
        });
        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 213, 25));

        jTextFieldFather.setColumns(2);
        jTextFieldFather.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        jTextFieldFather.setText("Father Name");
        jTextFieldFather.setOpaque(false);
        jPanel1.add(jTextFieldFather, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 213, 25));

        jTextFieldName.setColumns(2);
        jTextFieldName.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        jTextFieldName.setText("Name of Student");
        jTextFieldName.setOpaque(false);
        jPanel1.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 213, 25));

        jTextFieldCity.setColumns(2);
        jTextFieldCity.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        jTextFieldCity.setText("City");
        jTextFieldCity.setOpaque(false);
        jPanel1.add(jTextFieldCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 213, 25));

        jLabelTitle.setBackground(new java.awt.Color(102, 102, 255));
        jLabelTitle.setFont(new java.awt.Font("Sitka Subheading", 2, 18)); // NOI18N
        jPanel1.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 500, 37));

        jTextFieldAmount.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jTextFieldAmount.setText("Amount");
        jTextFieldAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldAmountFocusGained(evt);
            }
        });
        jPanel1.add(jTextFieldAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 130, 40));

        cancelButton.setBackground(new java.awt.Color(153, 0, 0));
        cancelButton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 130, 40));

        jLabelTitle1.setBackground(new java.awt.Color(102, 102, 255));
        jLabelTitle1.setFont(new java.awt.Font("Sitka Subheading", 2, 18)); // NOI18N
        jLabelTitle1.setText("Contact");
        jPanel1.add(jLabelTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 110, 20));

        payButton.setBackground(new java.awt.Color(0, 153, 0));
        payButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        payButton.setForeground(new java.awt.Color(255, 255, 255));
        payButton.setText("Pay");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });
        jPanel1.add(payButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 130, 40));

        purposeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACADEMIC", "EXAM FEE", "FINE", "OTHER", " " }));
        jPanel1.add(purposeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 90, 20));

        jTextFieldcontact.setColumns(2);
        jTextFieldcontact.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        jTextFieldcontact.setText("Contact");
        jTextFieldcontact.setOpaque(false);
        jPanel1.add(jTextFieldcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 213, 25));

        jComboBoxThrough.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASH", "CHEQUE", "OTHER" }));
        jPanel1.add(jComboBoxThrough, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 100, 20));

        jLabelTitle2.setBackground(new java.awt.Color(102, 102, 255));
        jLabelTitle2.setFont(new java.awt.Font("Sitka Subheading", 2, 18)); // NOI18N
        jLabelTitle2.setText("Roll Number");
        jPanel1.add(jLabelTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 110, 20));

        jLabelTitle3.setBackground(new java.awt.Color(102, 102, 255));
        jLabelTitle3.setFont(new java.awt.Font("Sitka Subheading", 2, 18)); // NOI18N
        jLabelTitle3.setText("City");
        jPanel1.add(jLabelTitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 110, 20));

        jLabelTitle4.setBackground(new java.awt.Color(102, 102, 255));
        jLabelTitle4.setFont(new java.awt.Font("Sitka Subheading", 2, 18)); // NOI18N
        jLabelTitle4.setText("Father Name");
        jPanel1.add(jLabelTitle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 110, 20));

        jTabbedPane1.addTab("Fees Pay", jPanel1);

        updateFees.setForeground(new java.awt.Color(0, 153, 0));
        updateFees.setMaximumSize(new java.awt.Dimension(486, 300));
        updateFees.setMinimumSize(new java.awt.Dimension(486, 300));
        updateFees.setOpaque(false);
        updateFees.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxClass2.setBackground(new java.awt.Color(0, 0, 0));
        jComboBoxClass2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jComboBoxClass2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxClass2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nursary", "Kg-1", "Kg-2", "Class 1", "Class 2", "Class 3", "Class 4", "Class 5", "Class 6", "Class 7", "Class 8", "Class 9", "Class 10", "Class 11", "Class 12" }));
        updateFees.add(jComboBoxClass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 100, 40));

        jTextFieldAmount2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextFieldAmount2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAmount2ActionPerformed(evt);
            }
        });
        updateFees.add(jTextFieldAmount2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 120, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Class");
        updateFees.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Amount");
        updateFees.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 153, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setForeground(java.awt.Color.white);
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        updateFees.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 90, 40));

        schoolNameLabel.setBackground(new java.awt.Color(102, 102, 255));
        schoolNameLabel.setFont(new java.awt.Font("Sitka Subheading", 2, 18)); // NOI18N
        updateFees.add(schoolNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 500, 37));

        jTabbedPane1.addTab("Fees Table", updateFees);

        studentFees.setMaximumSize(new java.awt.Dimension(486, 300));
        studentFees.setMinimumSize(new java.awt.Dimension(486, 300));
        studentFees.setOpaque(false);
        studentFees.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldAmount3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        studentFees.add(jTextFieldAmount3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 110, 40));

        jTextFieldId3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextFieldId3.setToolTipText("");
        studentFees.add(jTextFieldId3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 120, 40));

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        studentFees.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 90, 40));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Amount");
        studentFees.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Scholar Number");
        studentFees.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        schoolNameLabel1.setBackground(new java.awt.Color(102, 102, 255));
        schoolNameLabel1.setFont(new java.awt.Font("Sitka Subheading", 2, 18)); // NOI18N
        studentFees.add(schoolNameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 37));

        jTabbedPane1.addTab("Student Fess", studentFees);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 340));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login-background.jpg"))); // NOI18N
        background.setText("jLabel1");
        background.setMaximumSize(new java.awt.Dimension(486, 300));
        background.setMinimumSize(new java.awt.Dimension(486, 300));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 510, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        feesPay();
        // TODO add your handling code here:
    }//GEN-LAST:event_payButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void jTextFieldAmountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAmountFocusGained
        jTextFieldAmount.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAmountFocusGained

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        getDetails(Integer.valueOf(jTextFieldID.getText()));
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jTextFieldIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldIDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDMouseClicked

    private void jTextFieldIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIDFocusLost

    }//GEN-LAST:event_jTextFieldIDFocusLost

    private void jTextFieldIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIDFocusGained
        jTextFieldID.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDFocusGained

    private void jTextFieldRollNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRollNoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRollNoFocusGained

    private void jTextFieldRollNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRollNoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRollNoFocusLost

    private void jTextFieldRollNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldRollNoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRollNoMouseClicked

    private void jTextFieldRollNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRollNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRollNoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try{
             int cl;
             double fees;
             String classcat="0";
             int index = jComboBoxClass2.getSelectedIndex();
             fees = Double.parseDouble(jTextFieldAmount2.getText());
             if(index >=0 && index <=2){
                cl = 0;
                switch(index){
                    case 0:
                        classcat = "N";
                    break;
                    case 1:
                        classcat = "K1";
                    break;
                    case 2:
                        classcat = "K2";
                    break;
                }
             }
             else{
                 cl = index - 2;
             }
             if(fees <= 0){
                 JOptionPane.showMessageDialog(this, "Enter Valid Amount.");
                 return;
             }
             if(new Sql(this).setFees(cl, classcat, fees)){
                 JOptionPane.showMessageDialog(this, "FEES Updated");
             }
             else{
                 JOptionPane.showMessageDialog(this, "FEES CAN NOT Update! TRY Again");
             }
             
         }
         catch(Exception e){
            e.printStackTrace();
         }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            int id = Integer.parseInt(jTextFieldId3.getText());
            double amount = Double.parseDouble(jTextFieldAmount3.getText());
            if(new Sql(this).setStudentFees(id, amount))
                JOptionPane.showMessageDialog(this, "Fees Updated.");
            else 
                JOptionPane.showMessageDialog(this, "Fees Cannot  Updated.");       
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Cannot Update Fees.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldAmount2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAmount2ActionPerformed
         try{
             int cl;
             double fees;
             String classcat="0";
             int index = jComboBoxClass2.getSelectedIndex();
             fees = Double.parseDouble(jTextFieldAmount2.getText());
             if(index >=0 && index <=2){
                cl = 0;
                switch(index){
                    case 0:
                        classcat = "N";
                    break;
                    case 1:
                        classcat = "K1";
                    break;
                    case 2:
                        classcat = "K2";
                    break;
                }
             }
             else{
                 cl = index - 2;
             }
             if(fees <= 0){
                 JOptionPane.showMessageDialog(this, "Enter Valid Amount.");
                 return;
             }
             if(new Sql(this).setFees(cl, classcat, fees)){
                 JOptionPane.showMessageDialog(this, "FEES Updated");
             }
             else{
                 JOptionPane.showMessageDialog(this, "FEES CAN NOT Update! TRY Again");
             }
             
         }
         catch(Exception e){
            e.printStackTrace();
         }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAmount2ActionPerformed
public void getDetails(int id){
       Student st = new Sql(this).getStudentByID(id);
       jTextFieldRollNo.setText(String.valueOf(st.getRollNo()));
       jTextFieldCity.setText(st.getCity());
       jTextFieldName.setText(st.getFname());
       jTextFieldcontact.setText(st.getStudentContact());
       jTextFieldFather.setText(st.getFatherName());
       try{
           jLabelPhoto.setIcon(new ImageIcon(getClass().getResource("/images/"+id+".png")));
       }
           catch(Exception e){
               jLabelPhoto.setIcon(new ImageIcon(getClass().getResource("/images/warning_icon.gif")));
               e.printStackTrace();
       }
}


    
    public void feesPay(){
String roll_no;
int id;
double amount;
    try{
    id = Integer.valueOf(jTextFieldID.getText());
    amount= Double.valueOf(jTextFieldAmount.getText());
    Student st = new Sql(this).getStudentByID(id);
    double fees =  st.getFees();
    fees = fees -  amount;
    Sql sql = new Sql(this);
    Report rp = new Report();
    rp.setId(id);
    rp.setAmount(amount);
    rp.setComment(jTextFieldComment.getText());
    rp.setThrough(jComboBoxThrough.getSelectedItem().toString());
    rp.setName(jTextFieldName.getText());
    rp.setsClass(st.getStudentClass());
    rp.setContactNo(jTextFieldcontact.getText());
    rp.setPurpose(purposeComboBox.getSelectedItem().toString());
    rp.setClasscat(st.getClassCat());
    sql.insertFees(rp);
    
    JOptionPane.showMessageDialog(this, "Fees Paid ","Done",NORMAL);
    }
catch(Exception e){
JOptionPane.showMessageDialog(this, "Enter valid Amount","Error",JOptionPane.ERROR_MESSAGE);
}
    
    
}
public void printRecipt(){
    JTextPane jp = new JTextPane();
    jp.setText("\t\t"+SchoolMgmt.schoolName+"\n"+
            "\t\tRECIPT \n");
}    
    public void initData(){
jLabelTitle.setText(SchoolMgmt.schoolName);
schoolNameLabel.setText(SchoolMgmt.schoolName);
schoolNameLabel1.setText(SchoolMgmt.schoolName);

}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxClass2;
    private javax.swing.JComboBox<String> jComboBoxThrough;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelPhoto;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitle1;
    private javax.swing.JLabel jLabelTitle2;
    private javax.swing.JLabel jLabelTitle3;
    private javax.swing.JLabel jLabelTitle4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldAmount;
    private javax.swing.JTextField jTextFieldAmount2;
    private javax.swing.JTextField jTextFieldAmount3;
    private javax.swing.JTextField jTextFieldCity;
    private javax.swing.JTextField jTextFieldComment;
    private javax.swing.JTextField jTextFieldFather;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldId3;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldRollNo;
    private javax.swing.JTextField jTextFieldcontact;
    private javax.swing.JButton payButton;
    private javax.swing.JComboBox<String> purposeComboBox;
    private javax.swing.JLabel schoolNameLabel;
    private javax.swing.JLabel schoolNameLabel1;
    private javax.swing.JPanel studentFees;
    private javax.swing.JPanel updateFees;
    // End of variables declaration//GEN-END:variables
}
