/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmgmt;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author kapil
 */

public class LoginWindow extends javax.swing.JFrame {

    /**
     * Creates new form LoginWindow
     */
    public LoginWindow() {
        initComponents();
        
        setVisible(true);
        setLocation(420, 200);
        setResizable(false);
        
        labelSchoolName.setText(SchoolMgmt.schoolName);
        setTitle("School Management Software : Developed By Kapil Vishwakarma");
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username_text = new javax.swing.JTextField();
        labelSchoolName = new javax.swing.JLabel();
        button_login = new javax.swing.JButton();
        username_label = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        copyright_text = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username_text.setBackground(new java.awt.Color(240, 240, 240));
        username_text.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        username_text.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        username_text.setOpaque(false);
        username_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_textActionPerformed(evt);
            }
        });
        getContentPane().add(username_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 200, 20));

        labelSchoolName.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        labelSchoolName.setForeground(new java.awt.Color(0, 0, 153));
        labelSchoolName.setText("School Name");
        getContentPane().add(labelSchoolName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        button_login.setBackground(new java.awt.Color(0, 0, 255));
        button_login.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button_login.setForeground(new java.awt.Color(255, 255, 255));
        button_login.setText("Log In");
        button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loginActionPerformed(evt);
            }
        });
        getContentPane().add(button_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 190, 80, 30));

        username_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        username_label.setText("Username");
        getContentPane().add(username_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        password_label.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        password_label.setText("Password");
        getContentPane().add(password_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));
        getContentPane().add(copyright_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Developed by Kapil Vishwakarma");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("School Management");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 170, 200));

        jPasswordField1.setBackground(new java.awt.Color(240, 240, 240));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 200, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("+91-9752250817");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loginActionPerformed
        if(username_text.getText().equals("kapil") && jPasswordField1.getText().equals("kapil")){
            this.hide();
            new MainWindow11();
            setExtendedState(MAXIMIZED_BOTH);
            
        }
        
        
        
    }//GEN-LAST:event_button_loginActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed

        // TODO add your handling code here:
          if(username_text.getText().equals("root") && jPasswordField1.getText().equals("root")){
            this.hide();
            new MainWindow11();
            setExtendedState(MAXIMIZED_BOTH);
          }else{
              JOptionPane.showMessageDialog(this, "Wrong Password or Username.");
          }

    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void username_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_textActionPerformed
        jPasswordField1.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_username_textActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_login;
    private javax.swing.JLabel copyright_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel labelSchoolName;
    private javax.swing.JLabel password_label;
    private javax.swing.JLabel username_label;
    private javax.swing.JTextField username_text;
    // End of variables declaration//GEN-END:variables

}
