/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmgmt;

import java.awt.Color;
import java.awt.Font;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JPopupMenu;
/**
 *
 * @author kapil
 */
public class Profiler extends javax.swing.JFrame {

    /**
     * Creates new form Profiler
     */
    public Profiler() {
        initComponents();
        initAction();
        setDetails(123);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroung1Label = new javax.swing.JLabel();
        rollNoJTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        studentImageLabel = new javax.swing.JLabel();
        schoolNameLabel = new javax.swing.JLabel();
        nameLable = new javax.swing.JLabel();
        rollNoValueLable = new javax.swing.JLabel();
        fatherNameLabel = new javax.swing.JLabel();
        scholarNoValueLabel = new javax.swing.JLabel();
        motherNameLabel = new javax.swing.JLabel();
        motherNameValueLabel = new javax.swing.JLabel();
        dobvaluelabel = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        eadharNumberlabel = new javax.swing.JLabel();
        samagraIdLabel = new javax.swing.JLabel();
        familyIdLabel = new javax.swing.JLabel();
        accountNoLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        nameLable1 = new javax.swing.JLabel();
        motherNameLabel1 = new javax.swing.JLabel();
        motherNameLabel2 = new javax.swing.JLabel();
        classValueLabel = new javax.swing.JLabel();
        samagraIdlueLabel = new javax.swing.JLabel();
        fatherNameValueLabel = new javax.swing.JLabel();
        nameValueLabel = new javax.swing.JLabel();
        motherNameValueLabel1 = new javax.swing.JLabel();
        schoolNameLabel2 = new javax.swing.JLabel();
        schoolNameLabel3 = new javax.swing.JLabel();
        accountNumberLabel1 = new javax.swing.JLabel();
        schoolNameLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        feesValueLabel = new javax.swing.JLabel();
        motherNameLabel3 = new javax.swing.JLabel();
        motherNameLabel4 = new javax.swing.JLabel();
        motherNameLabel5 = new javax.swing.JLabel();
        motherNameValueLabel2 = new javax.swing.JLabel();
        fatherNameLabel1 = new javax.swing.JLabel();
        nameLable2 = new javax.swing.JLabel();
        motherNameLabel6 = new javax.swing.JLabel();
        motherNameLabel7 = new javax.swing.JLabel();
        motherNameLabel8 = new javax.swing.JLabel();
        GenderVlueLabel = new javax.swing.JLabel();
        familyIdValueLabel = new javax.swing.JLabel();
        previousSchoolLabel = new javax.swing.JLabel();
        studentContactLabel = new javax.swing.JLabel();
        eadharNolueLabel = new javax.swing.JLabel();
        fatherContactLabel = new javax.swing.JLabel();
        emailValueLabel = new javax.swing.JLabel();
        bankNameLabel = new javax.swing.JLabel();
        accountNumberLabel3 = new javax.swing.JLabel();
        fessValueLabel1 = new javax.swing.JLabel();
        GenderVlueLabel1 = new javax.swing.JLabel();
        addressValueLabel = new javax.swing.JLabel();
        categryValueLabel = new javax.swing.JLabel();
        pincodeValueLabel = new javax.swing.JLabel();
        stateValueLabel = new javax.swing.JLabel();
        distValueLabel = new javax.swing.JLabel();
        cityValueLable = new javax.swing.JLabel();

        backgroung1Label.setBackground(new java.awt.Color(204, 204, 204));
        backgroung1Label.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rollNoJTextField.setBackground(new java.awt.Color(0, 0, 102));
        rollNoJTextField.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rollNoJTextField.setForeground(new java.awt.Color(255, 255, 255));
        rollNoJTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rollNoJTextFieldFocusGained(evt);
            }
        });
        rollNoJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollNoJTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(rollNoJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 90, 150, 30));

        jButton1.setBackground(new java.awt.Color(51, 204, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Get Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 90, 100, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Enter ID Number");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(975, 96, -1, -1));

        studentImageLabel.setForeground(new java.awt.Color(51, 51, 51));
        studentImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/warning_icon.gif"))); // NOI18N
        studentImageLabel.setText("jLabel1");
        studentImageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(studentImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 120, 150));

        schoolNameLabel.setBackground(new java.awt.Color(0, 51, 153));
        schoolNameLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        schoolNameLabel.setForeground(java.awt.Color.white);
        schoolNameLabel.setText("School Name");
        schoolNameLabel.setAlignmentY(0.0F);
        schoolNameLabel.setOpaque(true);
        getContentPane().add(schoolNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 80));

        nameLable.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        nameLable.setForeground(new java.awt.Color(51, 51, 51));
        nameLable.setText("Roll Number");
        getContentPane().add(nameLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 160, 30));

        rollNoValueLable.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        rollNoValueLable.setForeground(new java.awt.Color(51, 51, 51));
        rollNoValueLable.setText("Name");
        getContentPane().add(rollNoValueLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 350, 30));

        fatherNameLabel.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        fatherNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        fatherNameLabel.setText("Father Name");
        getContentPane().add(fatherNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 170, 30));

        scholarNoValueLabel.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        scholarNoValueLabel.setForeground(new java.awt.Color(51, 51, 51));
        scholarNoValueLabel.setText("Name");
        getContentPane().add(scholarNoValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 350, -1));

        motherNameLabel.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        motherNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        motherNameLabel.setText("Scholar Number");
        getContentPane().add(motherNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 190, -1));

        motherNameValueLabel.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        motherNameValueLabel.setForeground(new java.awt.Color(51, 51, 51));
        motherNameValueLabel.setText("Mother Name");
        getContentPane().add(motherNameValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 350, 30));

        dobvaluelabel.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        dobvaluelabel.setForeground(new java.awt.Color(51, 51, 51));
        dobvaluelabel.setText("Student Contact");
        getContentPane().add(dobvaluelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 445, 180, 30));

        contactLabel.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        contactLabel.setForeground(new java.awt.Color(51, 51, 51));
        contactLabel.setText("FatherContact");
        getContentPane().add(contactLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 418, 180, 30));

        eadharNumberlabel.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        eadharNumberlabel.setForeground(new java.awt.Color(51, 51, 51));
        eadharNumberlabel.setText("Eadhar Number");
        getContentPane().add(eadharNumberlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 167, 30));

        samagraIdLabel.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        samagraIdLabel.setForeground(new java.awt.Color(51, 51, 51));
        samagraIdLabel.setText("Samagra ID");
        getContentPane().add(samagraIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 418, 160, 30));

        familyIdLabel.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        familyIdLabel.setForeground(new java.awt.Color(51, 51, 51));
        familyIdLabel.setText("Family ID");
        getContentPane().add(familyIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 445, -1, -1));

        accountNoLabel.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        accountNoLabel.setForeground(new java.awt.Color(51, 51, 51));
        accountNoLabel.setText("Bank Name");
        getContentPane().add(accountNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 418, -1, -1));

        emailLabel.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(51, 51, 51));
        emailLabel.setText("Email");
        getContentPane().add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 165, 30));

        jLabel20.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Previous School");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, -1, -1));

        nameLable1.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        nameLable1.setForeground(new java.awt.Color(51, 51, 51));
        nameLable1.setText("Name of Student");
        getContentPane().add(nameLable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 180, 30));

        motherNameLabel1.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        motherNameLabel1.setForeground(new java.awt.Color(51, 51, 51));
        motherNameLabel1.setText("Class");
        getContentPane().add(motherNameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 160, 30));

        motherNameLabel2.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        motherNameLabel2.setForeground(new java.awt.Color(51, 51, 51));
        motherNameLabel2.setText("Gender");
        getContentPane().add(motherNameLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 160, 30));

        classValueLabel.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        classValueLabel.setForeground(new java.awt.Color(51, 51, 51));
        classValueLabel.setText("Name");
        getContentPane().add(classValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 350, 30));

        samagraIdlueLabel.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        samagraIdlueLabel.setForeground(new java.awt.Color(51, 51, 51));
        samagraIdlueLabel.setText("Name");
        getContentPane().add(samagraIdlueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 418, 280, 30));

        fatherNameValueLabel.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        fatherNameValueLabel.setForeground(new java.awt.Color(51, 51, 51));
        fatherNameValueLabel.setText("Name");
        getContentPane().add(fatherNameValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 350, 30));

        nameValueLabel.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        nameValueLabel.setForeground(new java.awt.Color(51, 51, 51));
        nameValueLabel.setText("Name");
        getContentPane().add(nameValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 350, 30));

        motherNameValueLabel1.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        motherNameValueLabel1.setForeground(new java.awt.Color(51, 51, 51));
        motherNameValueLabel1.setText("Mother Name");
        getContentPane().add(motherNameValueLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 180, 30));

        schoolNameLabel2.setBackground(new java.awt.Color(0, 0, 102));
        schoolNameLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        schoolNameLabel2.setForeground(java.awt.Color.white);
        schoolNameLabel2.setText("  Academic History");
        schoolNameLabel2.setAlignmentY(0.0F);
        schoolNameLabel2.setOpaque(true);
        getContentPane().add(schoolNameLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 1390, 30));

        schoolNameLabel3.setBackground(new java.awt.Color(0, 0, 102));
        schoolNameLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        schoolNameLabel3.setForeground(java.awt.Color.white);
        schoolNameLabel3.setText("  Student Profile");
        schoolNameLabel3.setAlignmentY(0.0F);
        schoolNameLabel3.setOpaque(true);
        getContentPane().add(schoolNameLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1390, 30));

        accountNumberLabel1.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        accountNumberLabel1.setForeground(new java.awt.Color(51, 51, 51));
        accountNumberLabel1.setText("Account No.");
        getContentPane().add(accountNumberLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 418, -1, -1));

        schoolNameLabel4.setBackground(new java.awt.Color(0, 0, 102));
        schoolNameLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        schoolNameLabel4.setForeground(java.awt.Color.white);
        schoolNameLabel4.setText("  Contact Details And Other");
        schoolNameLabel4.setToolTipText("");
        schoolNameLabel4.setAlignmentY(0.0F);
        schoolNameLabel4.setOpaque(true);
        getContentPane().add(schoolNameLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 1390, 30));

        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Class", "Percentage", "Year", "Board", "School"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 1390, 140));

        feesValueLabel.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        feesValueLabel.setForeground(new java.awt.Color(51, 51, 51));
        feesValueLabel.setText("Na");
        getContentPane().add(feesValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 350, 30));

        motherNameLabel3.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        motherNameLabel3.setForeground(new java.awt.Color(51, 51, 51));
        motherNameLabel3.setText("Due Fees");
        getContentPane().add(motherNameLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 160, 30));

        motherNameLabel4.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        motherNameLabel4.setForeground(new java.awt.Color(51, 51, 51));
        motherNameLabel4.setText("Gender");
        getContentPane().add(motherNameLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 300, 160, 30));

        motherNameLabel5.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        motherNameLabel5.setForeground(new java.awt.Color(51, 51, 51));
        motherNameLabel5.setText("Address");
        getContentPane().add(motherNameLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, 160, 30));

        motherNameValueLabel2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        motherNameValueLabel2.setForeground(new java.awt.Color(51, 51, 51));
        motherNameValueLabel2.setText("Mother Name");
        getContentPane().add(motherNameValueLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 300, 290, 30));

        fatherNameLabel1.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        fatherNameLabel1.setForeground(new java.awt.Color(51, 51, 51));
        fatherNameLabel1.setText("PinCode");
        getContentPane().add(fatherNameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 170, 30));

        nameLable2.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        nameLable2.setForeground(new java.awt.Color(51, 51, 51));
        nameLable2.setText("State");
        getContentPane().add(nameLable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 210, 180, 30));

        motherNameLabel6.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        motherNameLabel6.setForeground(new java.awt.Color(51, 51, 51));
        motherNameLabel6.setText("City/Town");
        getContentPane().add(motherNameLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, 190, -1));

        motherNameLabel7.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        motherNameLabel7.setForeground(new java.awt.Color(51, 51, 51));
        motherNameLabel7.setText("Due Fees");
        getContentPane().add(motherNameLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 160, 30));

        motherNameLabel8.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        motherNameLabel8.setForeground(new java.awt.Color(51, 51, 51));
        motherNameLabel8.setText("District");
        getContentPane().add(motherNameLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, 190, -1));

        GenderVlueLabel.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        GenderVlueLabel.setForeground(new java.awt.Color(51, 51, 51));
        GenderVlueLabel.setText("Name");
        getContentPane().add(GenderVlueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 350, 30));

        familyIdValueLabel.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        familyIdValueLabel.setForeground(new java.awt.Color(51, 51, 51));
        familyIdValueLabel.setText("Name");
        getContentPane().add(familyIdValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 445, 280, 30));

        previousSchoolLabel.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        previousSchoolLabel.setForeground(new java.awt.Color(51, 51, 51));
        previousSchoolLabel.setText("Name");
        getContentPane().add(previousSchoolLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 290, 30));

        studentContactLabel.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        studentContactLabel.setForeground(new java.awt.Color(51, 51, 51));
        studentContactLabel.setText("Name");
        getContentPane().add(studentContactLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 445, 230, 30));

        eadharNolueLabel.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        eadharNolueLabel.setForeground(new java.awt.Color(51, 51, 51));
        eadharNolueLabel.setText("Name");
        getContentPane().add(eadharNolueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 280, 30));

        fatherContactLabel.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        fatherContactLabel.setForeground(new java.awt.Color(51, 51, 51));
        fatherContactLabel.setText("Name");
        getContentPane().add(fatherContactLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 418, 230, 30));

        emailValueLabel.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        emailValueLabel.setForeground(new java.awt.Color(51, 51, 51));
        emailValueLabel.setText("Name");
        getContentPane().add(emailValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 380, 30));

        bankNameLabel.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        bankNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        bankNameLabel.setText("Bank Name");
        getContentPane().add(bankNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 445, -1, -1));

        accountNumberLabel3.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        accountNumberLabel3.setForeground(new java.awt.Color(51, 51, 51));
        accountNumberLabel3.setText("Bank Name");
        getContentPane().add(accountNumberLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 445, -1, -1));

        fessValueLabel1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        fessValueLabel1.setForeground(new java.awt.Color(51, 51, 51));
        fessValueLabel1.setText("Na");
        getContentPane().add(fessValueLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 330, 290, 30));

        GenderVlueLabel1.setFont(new java.awt.Font("Swis721 BT", 1, 18)); // NOI18N
        GenderVlueLabel1.setForeground(new java.awt.Color(51, 51, 51));
        GenderVlueLabel1.setText("Category");
        getContentPane().add(GenderVlueLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, 150, 30));

        addressValueLabel.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        addressValueLabel.setForeground(new java.awt.Color(51, 51, 51));
        addressValueLabel.setText("Name");
        addressValueLabel.setAutoscrolls(true);
        getContentPane().add(addressValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 270, 290, 30));

        categryValueLabel.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        categryValueLabel.setForeground(new java.awt.Color(51, 51, 51));
        categryValueLabel.setText("Mother Name");
        getContentPane().add(categryValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 120, 290, 30));

        pincodeValueLabel.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        pincodeValueLabel.setForeground(new java.awt.Color(51, 51, 51));
        pincodeValueLabel.setText("Name");
        getContentPane().add(pincodeValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 240, 290, 30));

        stateValueLabel.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        stateValueLabel.setForeground(new java.awt.Color(51, 51, 51));
        stateValueLabel.setText("Name");
        getContentPane().add(stateValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 210, 290, 30));

        distValueLabel.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        distValueLabel.setForeground(new java.awt.Color(51, 51, 51));
        distValueLabel.setText("Name");
        getContentPane().add(distValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 180, 290, -1));

        cityValueLable.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        cityValueLable.setForeground(new java.awt.Color(51, 51, 51));
        cityValueLable.setText("Name");
        getContentPane().add(cityValueLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 150, 290, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rollNoJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollNoJTextFieldActionPerformed
        setDetails(Integer.valueOf(rollNoJTextField.getText()));
        // TODO add your handling code here:
    }//GEN-LAST:event_rollNoJTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setDetails(Integer.valueOf(rollNoJTextField.getText()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rollNoJTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rollNoJTextFieldFocusGained
        rollNoJTextField.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_rollNoJTextFieldFocusGained

    /**
     * @param args the command line arguments
     */
    public void initAction(){
     this.setVisible(true);
     this.setExtendedState(MAXIMIZED_BOTH);
     this.setTitle("Profile of Students");
     schoolNameLabel.setText(SchoolMgmt.schoolName);
        DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
        jTable1.setFont(new Font("verdana",Font.BOLD,12));
        jTable1.setSelectionBackground(Color.BLUE);
        jTable1.setSelectionForeground(Color.white);
        jTable1.setRowHeight(20);
    }
    
    public void setDetails(int id){
        try{
        Student st = new Sql(this).getStudentByID(id);
    //setting all label with value..
    rollNoValueLable.setText(String.valueOf(st.getRollNo()));
    scholarNoValueLabel.setText(String.valueOf(st.getScholarNumber()));
    nameValueLabel.setText(st.getFname()+" "+st.getmName()+" "+st.getlName());
    fatherNameValueLabel.setText(st.getFatherName());
    motherNameValueLabel.setText(st.getMotherName());
    classValueLabel.setText(st.getStudentClass()+" ("+st.getClassCat()+")");
    GenderVlueLabel.setText(st.getGender());
    feesValueLabel.setText(String.valueOf(st.getFees()));
    categryValueLabel.setText(st.getCategory());
    cityValueLable.setText(st.getCity());
    distValueLabel.setText(st.getDist());
    stateValueLabel.setText(st.getState());
    pincodeValueLabel.setText(st.getPinCode());
    addressValueLabel.setText(st.getLocalAddress());
    eadharNolueLabel.setText(st.getEadharNo());
    samagraIdlueLabel.setText(st.getSamagraId());
    familyIdValueLabel.setText(st.getFamilyId());
    previousSchoolLabel.setText(st.getPreviousSchool());
    emailValueLabel.setText(st.getEmail());
    fatherContactLabel.setText(st.getFatherContact());
    studentContactLabel.setText(st.getStudentContact());
    bankNameLabel.setText(st.getBankName());
    accountNoLabel.setText(st.getAccountNumber());
    setTable(id);
        try{
            studentImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+id+".jpg")));
        }catch(Exception e){
            studentImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/warning_icon.gif")));
            e.printStackTrace();
        }
        }
    catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, "Student NOT Found","Error",1);
        e.printStackTrace();
    }
    }
    
    private void setTable(int sid){
        try{
            //seting layout of table
            jTable1.getColumnModel().getColumn(0).setMaxWidth(200);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(500);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(500);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(500);
            
            //adding rows in table
            LinkedList<StudentDetails> list = new Sql(this).getStudentDetails(sid);
            DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
            
            for(int i=0;i<list.size();i++){
                StudentDetails sd = list.get(i);
                String[] row = {String.valueOf(sd.getId()), String.valueOf(sd.getCl()),String.valueOf(sd.getPercentage()),String.valueOf(sd.getYear()),sd.getBoard(),sd.getSchool() };
                df.addRow(row);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Cannot set Scholar details.");
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GenderVlueLabel;
    private javax.swing.JLabel GenderVlueLabel1;
    private javax.swing.JLabel accountNoLabel;
    private javax.swing.JLabel accountNumberLabel1;
    private javax.swing.JLabel accountNumberLabel3;
    private javax.swing.JLabel addressValueLabel;
    private javax.swing.JLabel backgroung1Label;
    private javax.swing.JLabel bankNameLabel;
    private javax.swing.JLabel categryValueLabel;
    private javax.swing.JLabel cityValueLable;
    private javax.swing.JLabel classValueLabel;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JLabel distValueLabel;
    private javax.swing.JLabel dobvaluelabel;
    private javax.swing.JLabel eadharNolueLabel;
    private javax.swing.JLabel eadharNumberlabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailValueLabel;
    private javax.swing.JLabel familyIdLabel;
    private javax.swing.JLabel familyIdValueLabel;
    private javax.swing.JLabel fatherContactLabel;
    private javax.swing.JLabel fatherNameLabel;
    private javax.swing.JLabel fatherNameLabel1;
    private javax.swing.JLabel fatherNameValueLabel;
    private javax.swing.JLabel feesValueLabel;
    private javax.swing.JLabel fessValueLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel motherNameLabel;
    private javax.swing.JLabel motherNameLabel1;
    private javax.swing.JLabel motherNameLabel2;
    private javax.swing.JLabel motherNameLabel3;
    private javax.swing.JLabel motherNameLabel4;
    private javax.swing.JLabel motherNameLabel5;
    private javax.swing.JLabel motherNameLabel6;
    private javax.swing.JLabel motherNameLabel7;
    private javax.swing.JLabel motherNameLabel8;
    private javax.swing.JLabel motherNameValueLabel;
    private javax.swing.JLabel motherNameValueLabel1;
    private javax.swing.JLabel motherNameValueLabel2;
    private javax.swing.JLabel nameLable;
    private javax.swing.JLabel nameLable1;
    private javax.swing.JLabel nameLable2;
    private javax.swing.JLabel nameValueLabel;
    private javax.swing.JLabel pincodeValueLabel;
    private javax.swing.JLabel previousSchoolLabel;
    private javax.swing.JTextField rollNoJTextField;
    private javax.swing.JLabel rollNoValueLable;
    private javax.swing.JLabel samagraIdLabel;
    private javax.swing.JLabel samagraIdlueLabel;
    private javax.swing.JLabel scholarNoValueLabel;
    private javax.swing.JLabel schoolNameLabel;
    private javax.swing.JLabel schoolNameLabel2;
    private javax.swing.JLabel schoolNameLabel3;
    private javax.swing.JLabel schoolNameLabel4;
    private javax.swing.JLabel stateValueLabel;
    private javax.swing.JLabel studentContactLabel;
    private javax.swing.JLabel studentImageLabel;
    // End of variables declaration//GEN-END:variables
}
