/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmgmt;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.text.MessageFormat;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
/**
 *
 * @author kapil
 */
public class Reports extends javax.swing.JFrame {

    /**
     * Creates new form Reports
     */
    public Reports() {
        initComponents();
        initAction();
        initData();
        setData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        schoolNameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBoxClass = new javax.swing.JComboBox<>();
        button_show = new javax.swing.JButton();
        removeStudentButton = new javax.swing.JButton();
        feesPayButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        addStudentButton = new javax.swing.JButton();
        reportsButton = new javax.swing.JButton();
        printReciptButton = new javax.swing.JButton();
        staffButton = new javax.swing.JButton();
        Settingsbutton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        jTextFieldDate2 = new javax.swing.JTextField();
        jTextFieldDate1 = new javax.swing.JTextField();
        jTextFieldReciptNumber = new javax.swing.JTextField();
        button_show1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        schoolNameLabel.setBackground(new java.awt.Color(0, 51, 153));
        schoolNameLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        schoolNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        schoolNameLabel.setText("School Name");
        schoolNameLabel.setOpaque(true);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(204, 204, 255));
        jScrollPane1.setViewportView(jTable1);

        jComboBoxClass.setBackground(new java.awt.Color(51, 51, 0));
        jComboBoxClass.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jComboBoxClass.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxClass.setAutoscrolls(true);
        jComboBoxClass.setOpaque(false);
        jComboBoxClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClassActionPerformed(evt);
            }
        });
        jComboBoxClass.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBoxClassPropertyChange(evt);
            }
        });
        jComboBoxClass.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jComboBoxClassVetoableChange(evt);
            }
        });

        button_show.setBackground(new java.awt.Color(51, 153, 0));
        button_show.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        button_show.setForeground(new java.awt.Color(255, 255, 255));
        button_show.setText("Show");
        button_show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_showMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_showMouseExited(evt);
            }
        });
        button_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_showActionPerformed(evt);
            }
        });

        removeStudentButton.setBackground(new java.awt.Color(153, 0, 51));
        removeStudentButton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        removeStudentButton.setForeground(new java.awt.Color(255, 255, 255));
        removeStudentButton.setText("Remove Student");
        removeStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStudentButtonActionPerformed(evt);
            }
        });

        feesPayButton.setBackground(new java.awt.Color(0, 204, 0));
        feesPayButton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        feesPayButton.setForeground(new java.awt.Color(255, 255, 255));
        feesPayButton.setText("Fees Pay");
        feesPayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feesPayButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("YYYY-MM-DD");

        addStudentButton.setBackground(new java.awt.Color(0, 51, 153));
        addStudentButton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        addStudentButton.setForeground(new java.awt.Color(255, 255, 255));
        addStudentButton.setText("Add Student");
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });

        reportsButton.setBackground(new java.awt.Color(153, 0, 153));
        reportsButton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        reportsButton.setForeground(new java.awt.Color(255, 255, 255));
        reportsButton.setText("Home");
        reportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsButtonActionPerformed(evt);
            }
        });

        printReciptButton.setBackground(new java.awt.Color(255, 102, 0));
        printReciptButton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        printReciptButton.setForeground(new java.awt.Color(255, 255, 255));
        printReciptButton.setText("Print Recipt");
        printReciptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printReciptButtonActionPerformed(evt);
            }
        });

        staffButton.setBackground(new java.awt.Color(0, 102, 102));
        staffButton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        staffButton.setForeground(new java.awt.Color(255, 255, 255));
        staffButton.setText("Staff");
        staffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffButtonActionPerformed(evt);
            }
        });

        Settingsbutton.setBackground(new java.awt.Color(0, 102, 204));
        Settingsbutton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        Settingsbutton.setForeground(new java.awt.Color(255, 255, 255));
        Settingsbutton.setText("Settings");
        Settingsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsbuttonActionPerformed(evt);
            }
        });

        printButton.setBackground(new java.awt.Color(51, 0, 51));
        printButton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        printButton.setForeground(new java.awt.Color(255, 255, 255));
        printButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printer.gif"))); // NOI18N
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        jTextFieldDate2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextFieldDate2.setText("2016/02/20");

        jTextFieldDate1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextFieldDate1.setText("2016/02/20");

        jTextFieldReciptNumber.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextFieldReciptNumber.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldReciptNumber.setText("Receipt Number");
        jTextFieldReciptNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldReciptNumberFocusGained(evt);
            }
        });

        button_show1.setBackground(new java.awt.Color(255, 102, 0));
        button_show1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        button_show1.setForeground(new java.awt.Color(255, 255, 255));
        button_show1.setText("Print");
        button_show1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_show1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_show1MouseExited(evt);
            }
        });
        button_show1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_show1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("YYYY-MM-DD");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("CLASS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(schoolNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(feesPayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(removeStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(reportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(staffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(printReciptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(Settingsbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxClass, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(button_show, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldReciptNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(button_show1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(schoolNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBoxClass)
                        .addComponent(jTextFieldDate1)
                        .addComponent(button_show, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(button_show1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldReciptNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(feesPayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printReciptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Settingsbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClassActionPerformed

    }//GEN-LAST:event_jComboBoxClassActionPerformed

    private void jComboBoxClassPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxClassPropertyChange

    }//GEN-LAST:event_jComboBoxClassPropertyChange

    private void jComboBoxClassVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jComboBoxClassVetoableChange

    }//GEN-LAST:event_jComboBoxClassVetoableChange

    private void button_showMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_showMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button_showMouseEntered

    private void button_showMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_showMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button_showMouseExited

    private void button_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_showActionPerformed
     this.showButton();
    }//GEN-LAST:event_button_showActionPerformed

    private void removeStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStudentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeStudentButtonActionPerformed

    private void feesPayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feesPayButtonActionPerformed
       feesPay();
        // TODO add your handling code here:
    }//GEN-LAST:event_feesPayButtonActionPerformed

    private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
        new AddStudent();
    }//GEN-LAST:event_addStudentButtonActionPerformed

    private void reportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsButtonActionPerformed
        this.hide();
        new MainWindow11();
    }//GEN-LAST:event_reportsButtonActionPerformed

    private void printReciptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printReciptButtonActionPerformed

        int id  = Integer.valueOf(JOptionPane.showInputDialog(this, "Enter the Recipt Number "));
        printRecipt(new Sql(this).getReportByReciptNumber(id));
        // TODO add your handling code here:
    }//GEN-LAST:event_printReciptButtonActionPerformed

    private void staffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffButtonActionPerformed
        new Staff();
        // TODO add your handling code here:
    }//GEN-LAST:event_staffButtonActionPerformed

    private void SettingsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SettingsbuttonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        try{
            jTable1.print(JTable.PrintMode.FIT_WIDTH,new MessageFormat("Students List"),new MessageFormat(SchoolMgmt.schoolName));
        }
        catch(Exception e){
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_printButtonActionPerformed

    private void button_show1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_show1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button_show1MouseEntered

    private void button_show1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_show1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button_show1MouseExited

    private void button_show1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_show1ActionPerformed
        try{
         int reciptNo = Integer.valueOf(jTextFieldReciptNumber.getText());
         Report rp = new Sql(this).getReportByReciptNumber(reciptNo);
            printRecipt(rp);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Cannot Print Recipt.");
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_button_show1ActionPerformed

    private void jTextFieldReciptNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldReciptNumberFocusGained
        jTextFieldReciptNumber.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldReciptNumberFocusGained

    /**
     * @param args the command line arguments
     */
public void initAction(){
    setVisible(true);
    setExtendedState(MAXIMIZED_BOTH);
    setTitle("Reports");
    schoolNameLabel.setText(SchoolMgmt.schoolName);
    table();
    setDefaultCloseOperation(EXIT_ON_CLOSE);
    jTable1.requestFocus();
}
public void table(){
    jTable1.removeAll();
    DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
     //df.getDataVector().removeAllElements();
     jTable1.setRowHeight(25);
     df.addColumn("Contact Number");
     df.addColumn("Amount");
     df.addColumn(" ");
     jTextFieldDate2.setText(SchoolMgmt.date);
     jTextFieldDate1.setText("2016-01-01");
     jTable1.getColumnModel().getColumn(0).setHeaderValue("Date");
     jTable1.getColumnModel().getColumn(1).setHeaderValue("Recipt Number");
     jTable1.getColumnModel().getColumn(2).setHeaderValue("Student ID");
     jTable1.getColumnModel().getColumn(3).setHeaderValue("Name");
     jTable1.getColumnModel().getColumn(4).setHeaderValue("Contact");
     jTable1.getColumnModel().getColumn(5).setHeaderValue("Purpose");
     jTable1.getColumnModel().getColumn(6).setHeaderValue("Amount");
     
     jTable1.getColumnModel().getColumn(0).setMinWidth(100);
     jTable1.getColumnModel().getColumn(0).setMaxWidth(200);
     
     jTable1.getColumnModel().getColumn(2).setMinWidth(100);
     jTable1.getColumnModel().getColumn(2).setMaxWidth(100);
     
     jTable1.getColumnModel().getColumn(1).setMinWidth(120);
     jTable1.getColumnModel().getColumn(1).setMaxWidth(120);
     
     jTable1.getColumnModel().getColumn(3).setMinWidth(300);
     jTable1.getColumnModel().getColumn(3).setMaxWidth(300);
     
     jTable1.getColumnModel().getColumn(4).setMinWidth(300);
     jTable1.getColumnModel().getColumn(4).setMaxWidth(300);
     
     
     
     
     /*df.addColumn("Contact number");
     df.addColumn("City/Town");
     df.addColumn("Fees");
     df.addColumn("Date");
     df.addColumn("Recipt No.");
     df.addColumn("Roll No.");
     df.addColumn("Name");
     df.addColumn("Amount");
*/
}

public void setData(){
    int count=0;
    Sql sql = new Sql(this);
    LinkedList<Report> rp = new LinkedList<>();
    double amount=0;
    String classcat="k";
    int cl;
    if(jComboBoxClass.getSelectedIndex()==1){
        cl=0;
        classcat ="N";
    }else if(jComboBoxClass.getSelectedIndex()==2){
        cl=0;
        classcat ="K1";
    }
    else if(jComboBoxClass.getSelectedIndex()==3){
        cl=0;
        classcat ="K2";
    }
    else{
       cl = jComboBoxClass.getSelectedIndex()-3;
    }
    
    System.out.println(""+jTextFieldDate1.getText()+" "+jTextFieldDate2.getText());
    if(jComboBoxClass.getSelectedIndex() == 0){
    rp = sql.getReports(jTextFieldDate1.getText(),jTextFieldDate2.getText());
    }else {
    rp = sql.getReportsByClass(jTextFieldDate1.getText(),jTextFieldDate2.getText(), cl, classcat);
    }
    DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
     jTable1.setFont(new Font("verdana",Font.BOLD,12));
     jTable1.setSelectionBackground(Color.BLUE);
     jTable1.setSelectionForeground(Color.white);
     df.getDataVector().removeAllElements();
    for(int i=0;i<rp.size();i++){
        Report r = rp.get(i);
         String rowData[] = {String.valueOf(r.getTime()),String.valueOf(r.getReciptNo()),String.valueOf(r.getId()),r.getName(),r.getContactNo(),r.getPurpose(),String.valueOf(r.getAmount())};
         df.addRow(rowData);
         amount+=r.getAmount();
         count++;
    }
    String rowData[] = {"","","","","Total Recipt : "+count,"Total",String.valueOf(amount)};
    df.addRow(rowData);
}
public void printRecipt(Report r){
    JTextArea jTextArea1 = new JTextArea();
    String cl=" ";
    int c = r.getsClass();
    String ccat = r.getClasscat();
    switch(c){
        case 0:
            switch(ccat){
                case "N":
                    cl ="Nursary";
                break;
                case "K1":
                    cl = "K1";
                break;
                case "K2":
                    cl = "K2";
                break;
            }
         break;
        case 1:
            cl = "1st";
        break;
        case 2:
            cl = "2nd";
        break;
        case 3:
            cl = "3rd";
        break;
        default:
            cl = c+"th";
        break;
        case 11:
            switch(ccat){
                case "M":
                     cl ="11th"+" Math Science";
                break;
                case "B":
                     cl ="11th"+" Bio";
                break;
                case "C":
                     cl ="11th"+" Commerce";
                break;
                case "Ag":
                     cl ="11th"+" Agriculture";
                break;
                case "Ar":
                     cl ="11th"+" Arts";
                break;
            }
        break;
        case 12:
            switch(ccat){
                case "M":
                     cl ="12th"+" Math Science";
                break;
                case "B":
                     cl ="12th"+" Bio";
                break;
                case "C":
                     cl ="12th"+" Commerce";
                break;
                case "Ag":
                     cl ="12th"+" Agriculture";
                break;
                case "Ar":
                     cl ="12th"+" Arts";
                break;
            }
        break;
    }
    jTextArea1.setText("\t\t Chandbad, Sehore (M.P.)\n"+"\t\t            Fee Recipt\n\n\n "+ 
                " Recipt Number : "+r.getReciptNo()+" \t\t\t Date : "+r.getTime()+"\n"+
             
                "______________________________________________________________________________________________________________________\n"
                + "\t\t\t\t\t Amount \n"+"\nPayed For "+r.getId()+""
            + "\nThrough "+r.getThrough()+"\t\t\t\t Rs. 4000/-\n"
                    +
                "Name : "+r.getName()+"\n"+
                  "Class "+cl+" \n"+
                "Contact : +91-"+r.getContactNo()+"\n"
                + "Purpose :  "+r.getPurpose()
                + "\n\n\n\n\n "+
                "______________________________________________________________________________________________________________________\n"
                + "\n\t\t\t\t\t Signature"
                );
        
        try{
            jTextArea1.print(new MessageFormat("Shree Gandhi Kabhir Higher Secoundary School"),new MessageFormat(" "));
        }catch(Exception e){
            e.printStackTrace();
        }
}
public void showButton(){
setData();
}

public void initData(){
jComboBoxClass.setBackground(Color.black);

jComboBoxClass.removeAllItems();
jComboBoxClass.addItem("Class");
jComboBoxClass.addItem("Nursary");
jComboBoxClass.addItem("KG - I");
jComboBoxClass.addItem("KG - II");
for(int i=1;i<=12;i++){
    jComboBoxClass.addItem("Class "+i);
}

}

public void feesPay(){
            int w=502,h=293;   
            JFrame frame = new FeesPay();
            frame.setTitle("Fees Pay");
            frame.setPreferredSize(new Dimension(w,h));
            frame.setMinimumSize(new Dimension(w,h));
            frame.setMaximumSize(new Dimension(w,h));
            frame.setLocation(350,190);
            frame.setVisible(true);
            frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Settingsbutton;
    private javax.swing.JButton addStudentButton;
    private javax.swing.JButton button_show;
    private javax.swing.JButton button_show1;
    private javax.swing.JButton feesPayButton;
    private javax.swing.JComboBox<String> jComboBoxClass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldDate1;
    private javax.swing.JTextField jTextFieldDate2;
    private javax.swing.JTextField jTextFieldReciptNumber;
    private javax.swing.JButton printButton;
    private javax.swing.JButton printReciptButton;
    private javax.swing.JButton removeStudentButton;
    private javax.swing.JButton reportsButton;
    private javax.swing.JLabel schoolNameLabel;
    private javax.swing.JButton staffButton;
    // End of variables declaration//GEN-END:variables
}
