/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmgmt;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author kapil
 */
public class ScholarDetails extends javax.swing.JFrame {

    /**
     * Creates new form FeesPay
     */
    public ScholarDetails() {
            
        initComponents();
        requestFocus();
        setVisible(true);
        this.setResizable(false);
        
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelPhoto = new javax.swing.JLabel();
        jTextFieldPercentage = new javax.swing.JTextField();
        jTextFieldRollNo = new javax.swing.JTextField();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldSchool = new javax.swing.JTextField();
        jLabelTitle = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        jLabelTitle1 = new javax.swing.JLabel();
        payButton = new javax.swing.JButton();
        jTextFieldYear = new javax.swing.JTextField();
        jLabelTitle2 = new javax.swing.JLabel();
        jLabelTitle3 = new javax.swing.JLabel();
        jLabelTitle4 = new javax.swing.JLabel();
        jComboBoxClass = new javax.swing.JComboBox<>();
        jTextFieldBoard = new javax.swing.JTextField();
        jLabelTitle5 = new javax.swing.JLabel();
        jLabelTitle6 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(700, 430));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(486, 300));
        jPanel1.setMinimumSize(new java.awt.Dimension(486, 300));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelPhoto.setBackground(new java.awt.Color(102, 255, 102));
        jLabelPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/warning_icon.gif"))); // NOI18N
        jPanel1.add(jLabelPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, 150));

        jTextFieldPercentage.setColumns(2);
        jTextFieldPercentage.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        jTextFieldPercentage.setText("Percentage");
        jTextFieldPercentage.setOpaque(false);
        jTextFieldPercentage.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPercentageFocusGained(evt);
            }
        });
        jPanel1.add(jTextFieldPercentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 213, 25));

        jTextFieldRollNo.setColumns(2);
        jTextFieldRollNo.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        jTextFieldRollNo.setText("Roll Number");
        jTextFieldRollNo.setOpaque(false);
        jTextFieldRollNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldRollNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldRollNoFocusLost(evt);
            }
        });
        jTextFieldRollNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldRollNoMouseClicked(evt);
            }
        });
        jTextFieldRollNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRollNoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldRollNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 110, 20));

        jTextFieldID.setColumns(2);
        jTextFieldID.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        jTextFieldID.setText("Student ID Number");
        jTextFieldID.setOpaque(false);
        jTextFieldID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldIDFocusLost(evt);
            }
        });
        jTextFieldID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldIDMouseClicked(evt);
            }
        });
        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 213, 25));

        jTextFieldName.setColumns(2);
        jTextFieldName.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        jTextFieldName.setText("Name of Student");
        jTextFieldName.setOpaque(false);
        jPanel1.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 213, 25));

        jTextFieldSchool.setColumns(2);
        jTextFieldSchool.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        jTextFieldSchool.setText("School");
        jTextFieldSchool.setOpaque(false);
        jPanel1.add(jTextFieldSchool, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 213, 25));

        jLabelTitle.setBackground(new java.awt.Color(102, 102, 255));
        jLabelTitle.setFont(new java.awt.Font("Sitka Subheading", 2, 18)); // NOI18N
        jPanel1.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 500, 37));

        cancelButton.setBackground(new java.awt.Color(153, 0, 0));
        cancelButton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 130, 40));

        jLabelTitle1.setBackground(new java.awt.Color(102, 102, 255));
        jLabelTitle1.setFont(new java.awt.Font("Sitka Subheading", 2, 18)); // NOI18N
        jLabelTitle1.setText("Passing Year");
        jPanel1.add(jLabelTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 110, 20));

        payButton.setBackground(new java.awt.Color(0, 153, 0));
        payButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        payButton.setForeground(new java.awt.Color(255, 255, 255));
        payButton.setText("Update");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });
        jPanel1.add(payButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 130, 40));

        jTextFieldYear.setColumns(2);
        jTextFieldYear.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        jTextFieldYear.setText("Year");
        jTextFieldYear.setOpaque(false);
        jTextFieldYear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldYearFocusGained(evt);
            }
        });
        jPanel1.add(jTextFieldYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 100, 25));

        jLabelTitle2.setBackground(new java.awt.Color(102, 102, 255));
        jLabelTitle2.setFont(new java.awt.Font("Sitka Subheading", 2, 18)); // NOI18N
        jLabelTitle2.setText("Roll Number");
        jPanel1.add(jLabelTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 110, 20));

        jLabelTitle3.setBackground(new java.awt.Color(102, 102, 255));
        jLabelTitle3.setFont(new java.awt.Font("Sitka Subheading", 2, 18)); // NOI18N
        jLabelTitle3.setText("Percentage");
        jPanel1.add(jLabelTitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 110, 20));

        jLabelTitle4.setBackground(new java.awt.Color(102, 102, 255));
        jLabelTitle4.setFont(new java.awt.Font("Sitka Subheading", 2, 18)); // NOI18N
        jLabelTitle4.setText("Enter Student Id");
        jPanel1.add(jLabelTitle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 150, 20));

        jComboBoxClass.setBackground(new java.awt.Color(0, 0, 0));
        jComboBoxClass.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jComboBoxClass.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nursary", "Kg-1", "Kg-2", "Class 1", "Class 2", "Class 3", "Class 4", "Class 5", "Class 6", "Class 7", "Class 8", "Class 9", "Class 10", "Class 11(M)", "Class 11(B)", "Class 11(C)", "Class 11(Ag)", "Class 11(Ar)", "Class 12(M)", "Class 12(B)", "Class 12(C)", "Class 12(Ag)", "Class 12(Ar)" }));
        jPanel1.add(jComboBoxClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 210, 20));

        jTextFieldBoard.setColumns(2);
        jTextFieldBoard.setFont(new java.awt.Font("Sitka Subheading", 3, 14)); // NOI18N
        jTextFieldBoard.setText("MP Board");
        jTextFieldBoard.setOpaque(false);
        jTextFieldBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBoardActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 90, 25));

        jLabelTitle5.setBackground(new java.awt.Color(102, 102, 255));
        jLabelTitle5.setFont(new java.awt.Font("Sitka Subheading", 2, 18)); // NOI18N
        jLabelTitle5.setText("Select Class");
        jPanel1.add(jLabelTitle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 110, 20));

        jLabelTitle6.setBackground(new java.awt.Color(102, 102, 255));
        jLabelTitle6.setFont(new java.awt.Font("Sitka Subheading", 2, 18)); // NOI18N
        jLabelTitle6.setText("School");
        jPanel1.add(jLabelTitle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 110, 20));

        jTabbedPane1.addTab("Scholar Details", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 340));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login-background.jpg"))); // NOI18N
        background.setText("jLabel1");
        background.setMaximumSize(new java.awt.Dimension(486, 300));
        background.setMinimumSize(new java.awt.Dimension(486, 300));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 510, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed

        // TODO add your handling code here:
        try{
            int id,cl,year;
            double per;
            String classcat,board,school;
            id=Integer.valueOf(jTextFieldID.getText());
            per = Double.valueOf(jTextFieldPercentage.getText());
            year = Integer.valueOf(jTextFieldYear.getText());
            board = jTextFieldBoard.getText();
            school = jTextFieldSchool.getText();
            int cSel = jComboBoxClass.getSelectedIndex();
            switch(cSel){
                case 0:
                    cl=0;
                    classcat="N";
                    break;
                case 1:
                    cl=0;
                    classcat="K1";
                    break;
                case 2:
                    cl=0;
                    classcat="K2";
                    break;
                case 13:
                    cl=11;
                    classcat="M";
                break;
                
                case 14:
                    cl=11;
                    classcat="B";
                break;
                
                case 15:
                    cl=11;
                    classcat="C";
                break;
                
                case 16:
                    cl=11;
                    classcat="Ag";
                break;
                case 17:
                    cl=11;
                    classcat="Ar";
                break;
                
                case 18:
                    cl=12;
                    classcat="M";
                break;
                
                case 19:
                    cl=12;
                    classcat="B";
                break;
                
                case 20:
                    cl=12;
                    classcat="C";
                break;
                
                case 21:
                    cl=12;
                    classcat="Ag";
                break;
                
                case 22:
                    cl=12;
                    classcat="Ar";
                break;
                
                    
                default:
                    cl = cSel-2;
                    classcat="k";
            }
            StudentDetails sd = new StudentDetails(id, year, cl, per, classcat, board, school);
            if(new Sql(this).addStudentDeatils(sd))
                JOptionPane.showMessageDialog(this, "Record Added Successfull.");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Cannot Update Detail!!!");
            e.printStackTrace();
        }
    }//GEN-LAST:event_payButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        try{
            int id = Integer.valueOf(jTextFieldID.getText());
            Student s = new Sql(this).getStudentByID(id);
            jTextFieldName.setText(s.getFname()+" "+s.getmName()+" "+s.getlName());
            jTextFieldRollNo.setText(String.valueOf(s.getRollNo()));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Student not Found.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jTextFieldIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldIDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDMouseClicked

    private void jTextFieldIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIDFocusLost

    }//GEN-LAST:event_jTextFieldIDFocusLost

    private void jTextFieldIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldIDFocusGained
        jTextFieldID.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDFocusGained

    private void jTextFieldRollNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRollNoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRollNoFocusGained

    private void jTextFieldRollNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRollNoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRollNoFocusLost

    private void jTextFieldRollNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldRollNoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRollNoMouseClicked

    private void jTextFieldRollNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRollNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRollNoActionPerformed

    private void jTextFieldBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBoardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBoardActionPerformed

    private void jTextFieldPercentageFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPercentageFocusGained
        jTextFieldPercentage.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPercentageFocusGained

    private void jTextFieldYearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldYearFocusGained
        jTextFieldYear.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldYearFocusGained
    public void init(){
        jLabelTitle.setText(SchoolMgmt.schoolName);
        jTextFieldSchool.setText(SchoolMgmt.schoolName);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> jComboBoxClass;
    private javax.swing.JLabel jLabelPhoto;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitle1;
    private javax.swing.JLabel jLabelTitle2;
    private javax.swing.JLabel jLabelTitle3;
    private javax.swing.JLabel jLabelTitle4;
    private javax.swing.JLabel jLabelTitle5;
    private javax.swing.JLabel jLabelTitle6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldBoard;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPercentage;
    private javax.swing.JTextField jTextFieldRollNo;
    private javax.swing.JTextField jTextFieldSchool;
    private javax.swing.JTextField jTextFieldYear;
    private javax.swing.JButton payButton;
    // End of variables declaration//GEN-END:variables
}
