/* 
 *To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 * add online sync button.
 */
package schoolmgmt;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.KeyAdapter;
import java.util.LinkedList;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseMotionAdapter;
import java.text.MessageFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.table.*;
import javax.swing.table.TableColumn;
/**
 *
 * @author kapil
 */
public class Staff extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
         Calendar cal;
        Date date;
        int month,year;
    
    public Staff() {
        date = new Date();
        cal = Calendar.getInstance();
        cal.setTime(date);
        year = cal.get(Calendar.YEAR);
        month = cal.get(Calendar.MONTH);
        
        initComponents();
        setVisible(true);
        setLocation(0, 0);
        setExtendedState(MAXIMIZED_BOTH);

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        newa(); 
        showButton(month+1,year);
        jTable1.requestFocus();
        checkForSalaryFunction(month,year);
    }

    /**
     * add two categories.
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        schoolNameLabel = new javax.swing.JLabel();
        printButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();
        staffPaymentButton = new javax.swing.JButton();
        attedanceButton = new javax.swing.JButton();
        addStudentButton = new javax.swing.JButton();
        removeFacultyButton = new javax.swing.JButton();
        reportsButton = new javax.swing.JButton();
        staffButton = new javax.swing.JButton();
        dateLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        search_text = new javax.swing.JTextField();
        button_search = new javax.swing.JButton();
        feesRadio = new javax.swing.JRadioButton();
        contactRadio = new javax.swing.JRadioButton();
        workingDaysLabel2 = new javax.swing.JLabel();
        workingDaysLabel1 = new javax.swing.JLabel();
        workingDaysLabel = new javax.swing.JLabel();
        jComboBoxMonth = new javax.swing.JComboBox<>();
        button_show = new javax.swing.JButton();
        jComboBoxYear = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        schoolNameLabel.setBackground(new java.awt.Color(0, 51, 153));
        schoolNameLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        schoolNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        schoolNameLabel.setText("School Name");
        schoolNameLabel.setOpaque(true);
        getContentPane().add(schoolNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 80));

        printButton.setBackground(new java.awt.Color(51, 0, 51));
        printButton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        printButton.setForeground(new java.awt.Color(255, 255, 255));
        printButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printer.gif"))); // NOI18N
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });
        getContentPane().add(printButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 630, 70, 50));

        aboutButton.setBackground(new java.awt.Color(0, 102, 204));
        aboutButton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        aboutButton.setForeground(new java.awt.Color(255, 255, 255));
        aboutButton.setText("Payment Report");
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(aboutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 630, 170, 50));

        staffPaymentButton.setBackground(new java.awt.Color(255, 102, 0));
        staffPaymentButton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        staffPaymentButton.setForeground(new java.awt.Color(255, 255, 255));
        staffPaymentButton.setText("Payment");
        staffPaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffPaymentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(staffPaymentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 630, 170, 50));

        attedanceButton.setBackground(new java.awt.Color(0, 204, 0));
        attedanceButton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        attedanceButton.setForeground(new java.awt.Color(255, 255, 255));
        attedanceButton.setText("Attendance");
        attedanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attedanceButtonActionPerformed(evt);
            }
        });
        getContentPane().add(attedanceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 630, 170, 50));

        addStudentButton.setBackground(new java.awt.Color(0, 51, 153));
        addStudentButton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        addStudentButton.setForeground(new java.awt.Color(255, 255, 255));
        addStudentButton.setText("Add Faculty");
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 170, 50));

        removeFacultyButton.setBackground(new java.awt.Color(153, 0, 51));
        removeFacultyButton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        removeFacultyButton.setForeground(new java.awt.Color(255, 255, 255));
        removeFacultyButton.setText("Remove Faculty");
        removeFacultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFacultyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(removeFacultyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 630, 170, 50));

        reportsButton.setBackground(new java.awt.Color(153, 0, 153));
        reportsButton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        reportsButton.setForeground(new java.awt.Color(255, 255, 255));
        reportsButton.setText("Reports");
        reportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(reportsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 630, 170, 50));

        staffButton.setBackground(new java.awt.Color(0, 102, 102));
        staffButton.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        staffButton.setForeground(new java.awt.Color(255, 255, 255));
        staffButton.setText("Home");
        staffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffButtonActionPerformed(evt);
            }
        });
        getContentPane().add(staffButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 630, 170, 50));

        dateLabel.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        dateLabel.setText("jLabel2");
        getContentPane().add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 150, 160, 40));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Faculty ID", "Name", "Contact", "Salary", "Amount to Pay", "Attendance This Month"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(204, 204, 255));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 190, 1340, 410));

        search_text.setText("Enter text");
        search_text.setOpaque(false);
        search_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                search_textFocusGained(evt);
            }
        });
        search_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_textActionPerformed(evt);
            }
        });
        getContentPane().add(search_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 110, 150, 26));

        button_search.setBackground(new java.awt.Color(0, 204, 0));
        button_search.setFont(new java.awt.Font("Vivaldi", 1, 18)); // NOI18N
        button_search.setForeground(new java.awt.Color(255, 255, 255));
        button_search.setText("Search");
        button_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_searchActionPerformed(evt);
            }
        });
        getContentPane().add(button_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 110, -1, 26));

        feesRadio.setText("Fees");
        feesRadio.setOpaque(false);
        getContentPane().add(feesRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 600, -1, -1));

        contactRadio.setText("Contact");
        contactRadio.setOpaque(false);
        getContentPane().add(contactRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 600, -1, -1));

        workingDaysLabel2.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        workingDaysLabel2.setText("Select Year");
        getContentPane().add(workingDaysLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 160, 20));

        workingDaysLabel1.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        workingDaysLabel1.setText("Select Month");
        getContentPane().add(workingDaysLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 160, 20));

        workingDaysLabel.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        workingDaysLabel.setText("jLabel2");
        getContentPane().add(workingDaysLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 150, 160, 40));

        jComboBoxMonth.setBackground(new java.awt.Color(51, 51, 0));
        jComboBoxMonth.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jComboBoxMonth.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jComboBoxMonth.setAutoscrolls(true);
        jComboBoxMonth.setOpaque(false);
        jComboBoxMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMonthActionPerformed(evt);
            }
        });
        jComboBoxMonth.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBoxMonthPropertyChange(evt);
            }
        });
        jComboBoxMonth.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jComboBoxMonthVetoableChange(evt);
            }
        });
        getContentPane().add(jComboBoxMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, 40));

        button_show.setBackground(new java.awt.Color(51, 153, 0));
        button_show.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        button_show.setForeground(new java.awt.Color(255, 255, 255));
        button_show.setText("Show");
        button_show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_showMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_showMouseExited(evt);
            }
        });
        button_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_showActionPerformed(evt);
            }
        });
        getContentPane().add(button_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 120, 40));

        jComboBoxYear.setBackground(new java.awt.Color(51, 51, 0));
        jComboBoxYear.setEditable(true);
        jComboBoxYear.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jComboBoxYear.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", " " }));
        jComboBoxYear.setAutoscrolls(true);
        jComboBoxYear.setOpaque(false);
        jComboBoxYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxYearActionPerformed(evt);
            }
        });
        jComboBoxYear.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBoxYearPropertyChange(evt);
            }
        });
        jComboBoxYear.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jComboBoxYearVetoableChange(evt);
            }
        });
        getContentPane().add(jComboBoxYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 120, 40));

        jLabel1.setBackground(new java.awt.Color(0, 102, 153));
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1390, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    public void initEvent(){;
    }
    
    private void search_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_textActionPerformed
       
// TODO add your handling code here:
    }//GEN-LAST:event_search_textActionPerformed

    private void button_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_searchActionPerformed
      
    }//GEN-LAST:event_button_searchActionPerformed

    private void search_textFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_textFocusGained
        search_text.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_search_textFocusGained

    private void attedanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attedanceButtonActionPerformed
        new SAttendance();        
    }//GEN-LAST:event_attedanceButtonActionPerformed

    
    private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
        new AddFaculty();
    }//GEN-LAST:event_addStudentButtonActionPerformed

    private void removeFacultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFacultyButtonActionPerformed
        int id;
        id = Integer.valueOf(JOptionPane.showInputDialog(this, "Enter Id of Teacher to remove ."));
        if(new Sql(this).removeFaculty(id)){
            JOptionPane.showMessageDialog(this,"Faculty Removed.");
        }else{
            JOptionPane.showMessageDialog(this, "Faculty Cannot remove.");
        }
        
        
    }//GEN-LAST:event_removeFacultyButtonActionPerformed

    private void reportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsButtonActionPerformed
    this.hide();
    new Reports();
    }//GEN-LAST:event_reportsButtonActionPerformed

    private void staffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffButtonActionPerformed
         this.dispose();
         new MainWindow11();
        // TODO add your handling code here:
    }//GEN-LAST:event_staffButtonActionPerformed

    private void staffPaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffPaymentButtonActionPerformed
       new StaffPayment();
        // TODO add your handling code here:
    }//GEN-LAST:event_staffPaymentButtonActionPerformed

    private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButtonActionPerformed
        new StaffReports();
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        try{
                 jTable1.print(JTable.PrintMode.FIT_WIDTH,new MessageFormat("Faculty List"),new MessageFormat(SchoolMgmt.schoolName));
          }
        catch(Exception e){
            e.printStackTrace();
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_printButtonActionPerformed

    private void jComboBoxMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMonthActionPerformed

    }//GEN-LAST:event_jComboBoxMonthActionPerformed

    private void jComboBoxMonthPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxMonthPropertyChange

    }//GEN-LAST:event_jComboBoxMonthPropertyChange

    private void jComboBoxMonthVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jComboBoxMonthVetoableChange

    }//GEN-LAST:event_jComboBoxMonthVetoableChange

    private void jComboBoxYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxYearActionPerformed

    private void jComboBoxYearPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxYearPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxYearPropertyChange

    private void jComboBoxYearVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jComboBoxYearVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxYearVetoableChange

    private void button_showMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_showMouseEntered
        button_show.setBackground(Color.green);
        // TODO add your handling code here:
    }//GEN-LAST:event_button_showMouseEntered

    private void button_showMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_showMouseExited
        button_show.setBackground(new Color(51,153,0));
        // TODO add your handling code here:
    }//GEN-LAST:event_button_showMouseExited

    private void button_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_showActionPerformed
        int m,y;
        m = jComboBoxMonth.getSelectedIndex()+1;
        y = Integer.valueOf(jComboBoxYear.getSelectedItem().toString());
        showButton(m,y);
        workingDaysLabel.setText("Working Days : "+(new Sql(this).getWorkingDays(m, y)));
    }//GEN-LAST:event_button_showActionPerformed
public void showButton(int month,int year){
    workingDaysLabel.setText("Working Days : "+new Sql(this).getWorkingDays(month, year));
    LinkedList<Teacher> list = new Sql().getTeachers();
    DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
    df.getDataVector().removeAllElements();
    for(int i=0;i<list.size();i++){
        Teacher t = list.get(i);
        int attendance = new Sql(this).getFacultyAttendance(t.getId(), month, year);
        
        String[] row = {String.valueOf(t.getId()),t.getName(),t.getContact(),String.valueOf(t.getSalary()),String.valueOf(t.getAmount()),String.valueOf(attendance)};
        df.addRow(row);
    }
}
private void checkForSalaryFunction(int month ,int year){
        int month_year = Integer.valueOf(month+""+year);
        System.out.println(""+month_year);
        boolean res  = new Sql(this).checkForSalaryMonth(month_year);
        if(res == true){
            int confrm = JOptionPane.showConfirmDialog(this, "Press OK to Update the Faculty Salary \n Month : "+month,"Cancel",2);
            System.out.println("schoolmgmt.Staff.checkForSalaryFunction()"+confrm);
            if(confrm == 0  ){
                salaryFunction(month, year);
                System.out.println("schoolmgmt.Staff.checkForSalaryFunction()");
            }
        }
}
private void salaryFunction(int month, int year){
        double total=0;
        Sql sql = new Sql(this);
        LinkedList<Teacher> teacherList = sql.getTeachers();
        for(int i=0;i<teacherList.size();i++){
              Teacher t = teacherList.get(i);
              double amount = sql.calculateMonthlySalary(t.getId(), month, year);
              sql.facultyAmountChange(t.getId(), amount);
              total += amount;
        }
        sql.addSalary(month, year, total);
}

public void feesPay(){
            int w=502,h=293;   
            JFrame frame = new FeesPay();
            frame.setTitle("Fees Pay");
            frame.setPreferredSize(new Dimension(w,h));
            frame.setMinimumSize(new Dimension(w,h));
            frame.setMaximumSize(new Dimension(w,h));
            frame.setLocation(350,190);
            frame.setVisible(true);
            frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
}
public void newa(){
        DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
        jTable1.setRowHeight(25);
        dateLabel.setText(SchoolMgmt.date);
        schoolNameLabel.setText("  "+SchoolMgmt.schoolName);
        this.setTitle("  "+"School Management");
     jTable1.getColumnModel().getColumn(0).setPreferredWidth(60);
     jTable1.getColumnModel().getColumn(0).setMinWidth(60);
     jTable1.getColumnModel().getColumn(0).setMaxWidth(60);
     jTable1.getColumnModel().getColumn(0).setResizable(false);
     
     jTable1.getColumnModel().getColumn(01).setPreferredWidth(250);
     jTable1.getColumnModel().getColumn(01).setMinWidth(250);
     jTable1.getColumnModel().getColumn(01).setMaxWidth(250);
     jTable1.getColumnModel().getColumn(01).setResizable(false);
     
     
     jTable1.getColumnModel().getColumn(02).setPreferredWidth(300);
     jTable1.getColumnModel().getColumn(02).setMinWidth(300);
     jTable1.getColumnModel().getColumn(02).setMaxWidth(350);
     jTable1.getColumnModel().getColumn(02).setResizable(false);
  
     
     jTable1.getColumnModel().getColumn(03).setPreferredWidth(300);
     jTable1.getColumnModel().getColumn(03).setMinWidth(300);
     jTable1.getColumnModel().getColumn(03).setMaxWidth(400);
     jTable1.getColumnModel().getColumn(03).setResizable(false);
     
     jTable1.getColumnModel().getColumn(04).setPreferredWidth(300);
     jTable1.getColumnModel().getColumn(04).setMinWidth(300);
     jTable1.getColumnModel().getColumn(04).setMaxWidth(400);
     jTable1.getColumnModel().getColumn(04).setResizable(false); 
      
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutButton;
    private javax.swing.JButton addStudentButton;
    private javax.swing.JButton attedanceButton;
    private javax.swing.JButton button_search;
    private javax.swing.JButton button_show;
    private javax.swing.JRadioButton contactRadio;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JRadioButton feesRadio;
    private javax.swing.JComboBox<String> jComboBoxMonth;
    private javax.swing.JComboBox<String> jComboBoxYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton printButton;
    private javax.swing.JButton removeFacultyButton;
    private javax.swing.JButton reportsButton;
    private javax.swing.JLabel schoolNameLabel;
    private javax.swing.JTextField search_text;
    private javax.swing.JButton staffButton;
    private javax.swing.JButton staffPaymentButton;
    private javax.swing.JLabel workingDaysLabel;
    private javax.swing.JLabel workingDaysLabel1;
    private javax.swing.JLabel workingDaysLabel2;
    // End of variables declaration//GEN-END:variables
}
